[build]
  publish = "."
  command = ""

# Redirects
[[redirects]]
  from = "/category/:category"
  to = "/category.html"
  status = 200

[[redirects]]
  from = "/article/:slug"
  to = "/article.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"